config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  devise_for :users
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'posts#index'
end

app/models/post.rb
require 'uri'
require 'net/http'
require 'openssl'
require 'base64'

class Post < ApplicationRecord

    validates :title,:category_id,:image, presence: true
    # validates :title, format: { with: /\A[a-zA-Z0-9-_]+\Z/, message: 'Title cannot contain whitespace or special characters' }

    belongs_to :user
    belongs_to :category

    has_one_attached :image
    has_one_attached :sound



    public
    # module_function

    def self.text_to_speech(text)
        voice = speech({
        'key' => '6474bf093c804dd6a0fd92ed8aac4519',
        'hl' => 'en-us',
        'v' => 'Mary',
        'src' => "#{text}",
        'r' => '0',
        'c' => 'mp3',
        'f' => '44khz_16bit_stereo',
        'ssml' => 'false',
        'b64' => 'false'
        })
        
        encoded_string = Base64.encode64(voice['response'])

        File.open('app/assets/audios/temp.mp3', "wb") do |file|
            file.write(Base64.decode64(encoded_string))
        end
        
        return "temp.mp3"
    end

    def self.attach_sound(post)
        post.sound.attach(io: File.open("app/assets/audios/temp.mp3"), filename: "#{post.title}.mp3")
    end    
    def self.speech(settings)
      _validate(settings)
      return _request(settings)
    end
    
    private
    
    def self._validate(settings)
      raise 'The settings are undefined' if settings.nil? || settings.empty?
      raise 'The API key is undefined' if settings['key'].nil? || settings['key'].empty?
      raise 'The text is undefined' if settings['src'].nil? || settings['src'].empty?
      raise 'The language is undefined' if settings['hl'].nil? || settings['hl'].empty?
    end
    
    def self._request(settings)
      response = {
        'error' => nil,
        'response' => nil
      }
          
      uri = URI((settings['ssl'] ? 'https' : 'http') + '://api.voicerss.org/')
      req = Net::HTTP::Post.new(uri)
      req.set_form_data(_buildRequest(settings))
        
      res = Net::HTTP.start(uri.hostname, uri.port,
        :use_ssl => uri.scheme == 'https') do |http|
        http.request(req)
      end
      
      case res
      when Net::HTTPSuccess
        if res.body.index('ERROR') == 0
          response['error'] = res.body
        else
          response['response'] = res.body
        end
      else
        response['error'] = res.message
      end
          
      response
    end
    
    def self._buildRequest(settings)
      return {
        'key' => settings['key'],
        'src' => settings['src'],
        'hl' => settings['hl'],
        'v' => settings['v'],
        'r' => settings['r'],
        'c' => settings['c'],
        'f' => settings['f'],
        'ssml' => settings['ssml'],
        'b64' => settings['b64']
      }
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @users = User.find_by_sql('Select * from users')

    if user_signed_in?
      @categoriez = Category.where(user_id: current_user.id)
      @cate = params[:cate]
      if !@cate.nil?
        @posts = Post.where(category_id: @cate, user_id: current_user.id)
      else
        @posts = Post.where(user_id: current_user.id)
      end
    end

  end

  def all_posts
    @posts = Post.where()
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    Post.text_to_speech(@post.title)
    Post.attach_sound(@post)
    

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      Post.text_to_speech(@post.title)
      Post.attach_sound(@post)
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :image, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

    def square(photo)
        photo.variant(:gravity=>"Center", resize: "500x500^", crop: "500x500+0+0")
    end

    def title(string)
        string = string.gsub(" ", "-")
    end

end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card mt-5">
    <div class="card-header">
      New Request
    </div>
    <div class="card-body">
      <div class="row">
        <div class="mb-3 col-6">
          <%= form.text_field :title, class:"form-control", placeholder:"Request Title" %>
        </div>
        <div class="mb-3 col-6">
          <% options = Category.where(user_id: current_user.id).map{|c| [c.category, c.id]} %>
          <% options.unshift(['Request Category', nil])%>
          <%= form.select(:category_id, options, {}, { :class => 'form-select' }) %>
        </div>
      </div>
      <div class="field form-group mb-3">
        <label class="form-label">Request Photo</label>
        <%= form.file_field :image, class:"form-control mb-4"%>
      </div>
    </div>
    
    <div class="card-footer text-muted">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/_header.html.erb
<nav class="navbar ps-4 pe-4" style="background-color:#a74ef5;">
    <% if user_signed_in? %>
        <ul class="navbar-nav me-auto mb-2">    
            <li class="nav-item">
                <% if current_user.avatar.attached?%>
                    <%= link_to(image_tag(square(current_user.avatar), class:"avatar"),root_path) %>
                <% else %>
                    <%= link_to(image_tag('default-avatar.jpg', class:"avatar"),root_path) %>
                <% end %>
            </li> 
        </ul>

        <% if !@categoriez.nil? %>
            <% @categoriez.each do |category| %>
                <ul class="navbar-nav me-auto mb-2">   

                    <li class="nav-item">
                        <div class="card">
                            <%= link_to image_tag(square(category.image), class:"category-pic"), posts_path(:cate => category.id), onclick:"playSound(event)", data:{audio: "#{category.category}"} %>
                            <%= audio_tag(polymorphic_path(category.sound), id: "#{category.category}")%>
                        </div>
                    </li> 
                </ul>
            <% end %>
        <% end %>
    <% else %>
        <ul class="navbar-nav me-auto mb-2 ps-5">
            <li class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
            </li>
        </ul>
    <% end %>
</nav>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="container mt-4">
    <div class="row">
      <div class="col-6">
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">Title</th>
              <td><%= post.title %></td>
            </tr>
            <tr>
              <th scope="row">Category</th>
              <td><%= post.category.category %></td>
            </tr>
            <tr>
              <td colspan="3"><%= audio_tag(polymorphic_path(post.sound), controls: true, class: "audio-play", id: "grapes") %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-6 justify-content-center text-center">
        <a class="p-1 audioButton" onclick="play('event')"> <%= image_tag(square(post.image), class:"request-pic") %> </a>
      </div>
    </div>
  </div>
</div>

<script>
    function play(element){
        var audio = document.getElementById(element);
        audio.currentTime = 0;
        audio.play();
    }
</script>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="container pt-5">
  <% if user_signed_in? %>
    <div class="row text-center">
      <div class="col justify-content-center">
        <% if current_page?(root_path)%>
            <% if @categoriez.count == 0 %>
              <div class="row">
                <%= link_to "Create a New Category", new_category_path, class:"btn btn-danger mb-5" %>
              </div>
              <div class="row">
                <% if current_user.avatar.attached?%>
                  <%= image_tag(square(current_user.avatar), class:"large-avatar") %>
                <% else %>
                  <h3> Consider uploading a photo so it can be used as a homepage icon above</h3>
                  <%= image_tag('default-avatar.jpg', class:"large-avatar") %>
                <% end %>              
              </div>
            <% else %>
              <div class="row row-cols-4">
                <% @categoriez.each do |category| %>
                  <div class="col mb-3">
                      <% title = category.category %>
                      <div class="col">
                        <div class="card">
                            <%= link_to image_tag(square(category.image), class:"request-pic"), posts_path(:cate => category.id), onclick:"playSound(event)", data:{audio: "#{category.category}"} %>
                            <%= audio_tag(polymorphic_path(category.sound), id: "#{category.category}")%>
                        </div>


                      </div>
                  </div>
                <% end %>              
              </div>

            <% end  %>          
        <% else %>
          <% if request.original_url.ends_with?("posts") %>
            <div class="row row-cols-4">
              <% @posts.each do |post| %>
                <div class="col mb-3">
                    <div class="col">
                      <%= link_to image_tag(square(post.image), class:"request-pic"), post %>
                    </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="row row-cols-4">
              <% @posts.each do |post| %>
                <div class="col mb-3">
                    <% title = title(post.title) %>
                    <div class="col">
                        <%= audio_tag(polymorphic_path(post.sound), class: "audio-play", id: "#{title}") %>
                        <a class="p-1 audioButton" onclick=<%= "play(\"#{title}\")"%> > <%= image_tag(square(post.image), class:"request-pic") %> </a>
                    </div>
                </div>
              <% end %>
              <% if @posts.count == 0 %>
                <div class="row">
                  <div class="col">
                    <%= link_to "Create a New Request", new_post_path, class:"btn btn-primary"  %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="row text-center">
      <div class="col justify-content-center">
        <%= image_tag('sophia-home.png', style:"width:400px !important;")%>
      </div>
    </div>
  <div class="row">
    <div class="col-12 justify-content-center">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center">Sophia's AAC</h5>
          <h6 class="card-subtitle mb-2 text-muted text-center">Phase IV</h6>
          <p class="card-text">This site was originally intended for Sophia, I've since decided to open 
          it up to the public so other's can benefit too. I've designed this for an iPad, it will work 
          on other devices, but will preform best on the safari browser on an iPad.<br><br>
          <strong>How To Use: </strong> Create one account per child, upload a profile image that will then be used as a logo/home button. 
          you will be prompted to create categories, once you have added your categories, create your requests and link them to the categories you've 
          already created. You will also need to upload a picture. Sound is auto-generated from the Title. <br><br>
          <strong>Questions? </strong> if you have a question or if you want to leave me a tip, my email is: mr.negm90@gmail.com This app is free, cloud storage 
          for photos, sounds, and users isn't. It would be nice if I don't go bankrupt in the process of trying to get my daughter vocal. <br><br></p>

          <p class="text-center"><strong>Thank you!</strong></p>

        </div>
        <div class="card-footer text-muted">
          <%= link_to "Create Your Account",new_user_registration_path, class:"btn btn-primary col-12" %>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center text-muted">
    <p>Current User Count: <%= @users.count %></p>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= render @post %>
<div class="row pt-5">
  <div class="col-12 mb-5">
     <%= link_to "Edit this post", edit_post_path(@post), class:"btn btn-primary btn-lg col-12 mb-4" %>
     <%= button_to "Destroy this post", @post, method: :delete, class:"btn btn-danger col-12" %>
  </div>
</div>