config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  devise_for :users
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'posts#index'
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning alert-dismissible fade show alert-<%= key %>">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sophia's ACC</title>
    <%= favicon_link_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%# <meta name="viewport" content="width=device-width,initial-scale=1"> %>
    <meta name="viewport" content="user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <div id="page-content">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    
      <%= render 'posts/header' %>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div> 
    </div>
  </body>
  <footer id="sticky-footer" class="flex-shrink-0">
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand bg-dark">
        <div class="container-fluid">
          <div class="collapse navbar-collapse text-white-50" id="navbarNav">
            <ul class="navbar-nav">
              <li class="list-group-item"><%= link_to "Home", root_path, style:"color:  #cc98fa !important;", class:"nav-link"  %></li>
              <li class="list-group-item"><%= link_to "New Category", new_category_path, style:"color:  #cc98fa !important;", class:"nav-link"  %></li>
              <li class="list-group-item"><%= link_to "New Request", new_post_path, style:"color:  #cc98fa !important;", class:"nav-link"  %></li>
              <li class="list-group-item"><%= link_to "Categories", categories_path, style:"color:  #cc98fa !important;", class:"nav-link"  %></li>
              <li class="list-group-item"><%= link_to "Requests", posts_path, style:"color:  #cc98fa !important;", class:"nav-link"  %></li>
            </ul>
            <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
              <li class="list-group-item"><%= link_to "Edit Account", edit_user_registration_path, style:"color:  #cc98fa !important;", class:"nav-link"  %></li>
              <li class="list-group-item"><%= link_to "Log out", destroy_user_session_path, style:"color: red !important;", class:"nav-link" %></li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
  </footer>

  <%# JS for TABS %>
  <script>
    function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
    }
  </script>

  <%# JS for sound on regular cards %>
  <script>
    function play(element){
        var audio = document.getElementById(element);
        // audio.currentTime = 0;
        audio.play();
    }
  </script>

  <%# JS for sound on redirect %>
  <script type="text/javascript">
    function playSound(event){
      console.log(event);

      event.preventDefault();

      const link = event.currentTarget;
      const audio = document.getElementById(link.dataset.audio)

      audio.onended = function() { window.location = link };

      audio.play();
    }
  </script>
</html>